package:
    name: cxxopts
    version: 1.4.1
source:
    fn: cxxopts-1.4.1.tar.gz
    patch:
        - 0001-Fixup-integer-pattern-multiple-definition.patch
    sha256: c5ccfe99bd3db0604d077c968b39a42d61333a64d171fe84d7037d6c0dcc996d
    url: https://github.com/jarro2783/cxxopts/archive/v1.4.1.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    string: '0'
requirements:
    build:
        - cmake
        - toolchain
    run: []
test:
    commands:
        - if exist %LIBRARY_INC%\\cxxopts.hpp (exit 0) else (exit 1)                                    # [win]
        - if exist %LIBRARY_LIB%\\cmake\\cxxopts\\cxxopts-config.cmake (exit 0) else (exit 1)           # [win]
        - if exist %LIBRARY_LIB%\\cmake\\cxxopts\\cxxopts-config-version.cmake (exit 0) else (exit 1)   # [win]
        - test -f ${PREFIX}/include/cxxopts.hpp                                                         # [unix]
        - test -f ${PREFIX}/lib/cmake/cxxopts/cxxopts-config.cmake                                      # [unix]
        - test -f ${PREFIX}/lib/cmake/cxxopts/cxxopts-config-version.cmake                              # [unix]
about:
    description: This is a lightweight C++ option parser library, supporting the standard
        GNU style syntax for options.
    dev_url: https://github.com/jarro2783/cxxopts
    doc_url: https://github.com/jarro2783/cxxopts
    home: https://github.com/jarro2783/cxxopts
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: A lightweight C++ option parser library
extra:
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - JohanMabille
        - gouarin
